-- Built-in exercises, visible to every user. To add more later, create a new
-- migration with `npx drizzle-kit generate --custom --name <name>`.
INSERT INTO "exercises" ("name", "muscle_group") VALUES
  ('Bench Press', 'chest'),
  ('Incline Bench Press', 'chest'),
  ('Decline Bench Press', 'chest'),
  ('Dumbbell Bench Press', 'chest'),
  ('Incline Dumbbell Press', 'chest'),
  ('Decline Dumbbell Press', 'chest'),
  ('Dumbbell Fly', 'chest'),
  ('Incline Dumbbell Fly', 'chest'),
  ('Cable Crossover', 'chest'),
  ('Pec Deck', 'chest'),
  ('Machine Chest Press', 'chest'),
  ('Push-Up', 'chest'),
  ('Dip', 'chest'),

  ('Deadlift', 'back'),
  ('Pull-Up', 'back'),
  ('Chin-Up', 'back'),
  ('Lat Pulldown', 'back'),
  ('Close-Grip Lat Pulldown', 'back'),
  ('Barbell Row', 'back'),
  ('Pendlay Row', 'back'),
  ('Dumbbell Row', 'back'),
  ('Seated Cable Row', 'back'),
  ('T-Bar Row', 'back'),
  ('Chest-Supported Row', 'back'),
  ('Machine Row', 'back'),
  ('Straight-Arm Pulldown', 'back'),
  ('Back Extension', 'back'),
  ('Barbell Shrug', 'back'),
  ('Dumbbell Shrug', 'back'),

  ('Overhead Press', 'shoulders'),
  ('Seated Dumbbell Shoulder Press', 'shoulders'),
  ('Arnold Press', 'shoulders'),
  ('Machine Shoulder Press', 'shoulders'),
  ('Lateral Raise', 'shoulders'),
  ('Cable Lateral Raise', 'shoulders'),
  ('Front Raise', 'shoulders'),
  ('Rear Delt Fly', 'shoulders'),
  ('Reverse Pec Deck', 'shoulders'),
  ('Face Pull', 'shoulders'),
  ('Upright Row', 'shoulders'),

  ('Barbell Curl', 'biceps'),
  ('EZ-Bar Curl', 'biceps'),
  ('Dumbbell Curl', 'biceps'),
  ('Hammer Curl', 'biceps'),
  ('Incline Dumbbell Curl', 'biceps'),
  ('Preacher Curl', 'biceps'),
  ('Cable Curl', 'biceps'),
  ('Concentration Curl', 'biceps'),

  ('Close-Grip Bench Press', 'triceps'),
  ('Skull Crusher', 'triceps'),
  ('Triceps Pushdown', 'triceps'),
  ('Rope Pushdown', 'triceps'),
  ('Overhead Dumbbell Triceps Extension', 'triceps'),
  ('Overhead Cable Triceps Extension', 'triceps'),
  ('Dumbbell Kickback', 'triceps'),
  ('Bench Dip', 'triceps'),

  ('Squat', 'quads'),
  ('Front Squat', 'quads'),
  ('Goblet Squat', 'quads'),
  ('Hack Squat', 'quads'),
  ('Leg Press', 'quads'),
  ('Bulgarian Split Squat', 'quads'),
  ('Lunge', 'quads'),
  ('Walking Lunge', 'quads'),
  ('Step-Up', 'quads'),
  ('Leg Extension', 'quads'),

  ('Romanian Deadlift', 'hamstrings'),
  ('Stiff-Leg Deadlift', 'hamstrings'),
  ('Good Morning', 'hamstrings'),
  ('Lying Leg Curl', 'hamstrings'),
  ('Seated Leg Curl', 'hamstrings'),

  ('Hip Thrust', 'glutes'),
  ('Glute Bridge', 'glutes'),
  ('Sumo Deadlift', 'glutes'),
  ('Cable Glute Kickback', 'glutes'),
  ('Hip Abduction Machine', 'glutes'),

  ('Standing Calf Raise', 'calves'),
  ('Seated Calf Raise', 'calves'),
  ('Leg Press Calf Raise', 'calves'),

  ('Hanging Leg Raise', 'core'),
  ('Cable Crunch', 'core'),
  ('Ab Wheel Rollout', 'core'),
  ('Crunch', 'core'),
  ('Decline Sit-Up', 'core'),
  ('Russian Twist', 'core');
